### ISSUE TITLE
magePalCoreNotificationsIcon.js fails to load on M2.4.0 in admin backend

### ISSUE THREAD

**Issue by n2diving-net** [magepal/magento2-edit-order-email#3]
magePalCoreNotificationsIcon.js fails to load on M2.4.0 in admin backend

Debug from Chrome console log...

JQMIGRATE: Migrate is installed with logging active, version 1.4.1
require.js:1895 GET 

https://www.example.com/pub/static/adminhtml/Magento/backend/en_US/magePalCoreNotificationIcon.js net::ERR_ABORTED 404

main.js:44 Error: Script error for: magePalCoreNotificationIcon
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)

**Comment by srenon** [comment]
@n2diving-dgx... I am not able to reproduce any issue on 2.4.0.

The path to that JS file should be:

 > example.come/pub/static/version1596032599/adminhtml/Magento/backend/en_US/MagePal_Core/js/notification-icon.js

See vendor/magepal/magento2-core/view/adminhtml/requirejs-config.js


![image](https://user-images.githubusercontent.com/1415141/91043958-841bb780-e5e2-11ea-9a2b-cddfa14c2bb9.png)

Try rerun setup:upgrade; di-compile and deploy static content (assuming you are in production mode)

**Comment by n2diving-net** [comment]
Yep, broken... but now I know why... clue was in your path vs mine... my M2.4 testing config has file signing OFF.   The extension is broken when Stores>Configuration>System>Developer>Static Files Settings> Sign Static Files=NO
 Also noticed other little weirdness...  missing icon in backend...
![magepal-1](https://user-images.githubusercontent.com/17930467/91080719-0ec8da80-e614-11ea-95bb-6ab61e7a8c21.JPG)
 
Set Sign Static Files = YES, clear cache... bug disappears and MagePal icon reappears.
