### ISSUE TITLE
No update in order address

### ISSUE THREAD

**Issue by visualwebs** [magepal/magento2-edit-order-email#6]
Hi. I was using this module for several projects and one customer detected a 3rd party retrieves still the old email after the change.
Inspecting the database I see the order address is not being changed.
Can add this feature in the code or make it as optional via configuration?

I´m using those lines in the controller after save the order, and is doing the job.

`foreach ($order->getAddressesCollection() as $address)
{
     $address->setEmail($emailAddress)->save();
}`

**Comment by srenon** [comment]
please upgrade to [1.1.7](https://github.com/magepal/magento2-edit-order-email/releases/tag/1.1.7)
