### ISSUE TITLE
Fails to install on M2.4.4 (php 8.1)

### ISSUE THREAD

**Issue by n2diving-net** [magepal/magento2-edit-order-email#8]
$ composer require --update-no-dev magepal/magento2-edit-order-email
Info from https://repo.packagist.org: #StandWithUkraine

  [InvalidArgumentException]
  Package magepal/magento2-edit-order-email has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - magepal/magento2-edit-order-email 1.1.6 requires php ~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0|~7.1.3|~7.2.0|~7.3.0|~7.4.0 which does not match your installed version 8.1.4.

**Comment by srenon** [comment]
Fixed in [1.1.7](https://github.com/magepal/magento2-edit-order-email/releases/tag/1.1.7)
